version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11
  slack: circleci/slack@3.3.0


jobs:
  build-and-deploy-frontend:
    docker:
      - image: 'circleci/node:11.11'
    steps:
      - checkout
      - run: yarn && yarn build
      - aws-s3/sync:
          from: build # local dir
          to: '${AWS_S3_BUCKET}'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
      # - slack/status:
      #     webhook: '${SLACK_WEBHOOK_URL}'

workflows:
  deploy-frontend-master:
    jobs:
      - build-and-deploy-frontend:
          filters:
            branches:
              only: master # only this branch will be built
