version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  build-and-deploy-to-s3:
    docker:
      - image: 'circleci/node:11.11'
    steps:
      - checkout
      - run: yarn && yarn build
      - run: ls
      - aws-s3/sync:
          from: ./dist # local dir
          to: s3://circle-frontend
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  deploy-frontend-master:
    jobs:
      - build-and-deploy-to-s3:
          filters:
            branches:
              only: master # only this branch will be built
